routes/web.php
<?php
use Illuminate\Support\Facades\Auth;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::group(function () {
    Route::middleware('user')->group(function () {
        Route::resource('department', DepartmentController::class);
        Route::resource('role', RoleController::class);
        Route::resource('employee', EmployeeController::class);
     });
// })
// ->middleware(['isAdmin' excep()]);
// Route::get('/department', [DepartmentController::class, 'index'])->name('home');
// Route::get('/department/create', [DepartmentController::class, 'create'])->name('home');
// Route::post('/department', [DepartmentController::class, 'store'])->name('home');
// Route::get('/department/', [HomeController::class, 'index'])->name('home');
// Route::get('/index', [HomeController::class, 'index'])->name('home');



Route::middleware(['user'])->group(function () {

});

//         Route::resource('department', DepartmentController::class);
//         Route::resource('role', RoleController::class);
//         Route::resource('employee', EmployeeController::class);

Route::get('/', function () {
    return view('index');
})->middleware(['user'])->name('dashboard');
require __DIR__.'/auth.php';
Route::post('login','LoginController@check');
Auth::routes();
Route::get('/index', [HomeController::class, 'index'])->name('home');
Route::controller(UserController::class)->group(function(){
    Route::get('users', 'index');
    Route::get('users-export', 'export')->name('users.export');
});

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="/song" method="post">
        @csrf
        Tên bài hát<br> <input type="text" name="tenBaiHat"><br>
        <button type="submit">Submit</button>
    </form>
</body>
</html>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="/song/{{ $song->id }}" method="post">
        @csrf
        @method('PUT')
        Tên bài hát<br> <input type="text" name="tenBaiHat" value="{{ $song -> tenBaiHat }}" ><br>
        <button type="submit">Update</button>
    </form>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.body')
@section('index')
<div class="content-wrapper" style="min-height: 165px;">
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Trang chủ</h1>
				</div><!-- /.col -->

			</div>
		</div>
	</div>
	<section class="content" >
		<div class="container-fluid" style="min-height:165px;" >
			<div class="row" style="weight:265px;">
				<div class="col-lg-3 col-6" >
					<!-- small box -->
					<div class="small-box bg-info"  style="weight:265px;" >
						<div class="inner">
							<h4>PHÒNG BAN</h4>
						</div>
						<div class="icon">
						</div>
						<a href="{{ route('department.index') }}" class="small-box-footer">Chi tiết <i class="fas fa-arrow-circle-right"></i></a>
					</div>
				</div>
				<!-- ./col -->
				<div class="col-lg-3 col-6">
					<!-- small box -->
					<div class="small-box bg-success">
						<div class="inner">
                        <h4>CHỨC VỤ</h4>
						</div>
						<div class="icon">
							<i class="ion ion-stats-bars"></i>
						</div>
						<a href="{{ route('role.index') }}" class="small-box-footer">Chi tiết <i class="fas fa-arrow-circle-right"></i></a>
					</div>
				</div>
				<!-- ./col -->
				<div class="col-lg-3 col-6">
					<!-- small box -->
					<div class="small-box bg-warning">
						<div class="inner">
							<h4 style="color: #fff">NHÂN VIÊN</h4>
						</div>
						<div class="icon">
							<i class="ion ion-person-add"></i>
						</div>
						<a href="{{ route('employee.index') }}" class="small-box-footer">Chi tiết <i class="fas fa-arrow-circle-right"></i></a>
					</div>
				</div>
				<!-- ./col -->
			</div>
		</div>
	</section>
</div>
@endsection

resources/views/song.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
<ul>
<h1>
    <button ><a href="/create">Thêm</a></button>
</h1>
    <table >
        <tr>
            <th>Ten Bai Hat</th>
        </tr>
        <tr>
            <td>
        @foreach ($songs as $song)
        <li style="list-style:nun">
        <div>
            {{ $song->tenBaiHat }}
        </div>
        <div>
            {{ $song->CaSi->tenCaSi }}
        </div>
        <a href="/song/{{ $song->id }}/edit">
            <button type="submit">Edit</button>
        </a>
        <form action="/{{ $song -> id  }}" method = "post" >
            @csrf
            @method('delete')
            <button type="submit">Delete</button>
        </form>
        </li>
        @endforeach
            </td>

    </tr>

    </table>
    {{ $songs->links()  }}

</ul>


</body>
</html>