routes/web.php
<?php
use Illuminate\Support\Facades\Auth;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::group(function () {
    Route::middleware('user')->group(function () {
        Route::resource('department', DepartmentController::class);
        Route::resource('role', RoleController::class);
        Route::resource('employee', EmployeeController::class);
     });
// })
// ->middleware(['isAdmin' excep()]);
// Route::get('/department', [DepartmentController::class, 'index'])->name('home');
// Route::get('/department/create', [DepartmentController::class, 'create'])->name('home');
// Route::post('/department', [DepartmentController::class, 'store'])->name('home');
// Route::get('/department/', [HomeController::class, 'index'])->name('home');
// Route::get('/index', [HomeController::class, 'index'])->name('home');



Route::middleware(['user'])->group(function () {

});

//         Route::resource('department', DepartmentController::class);
//         Route::resource('role', RoleController::class);
//         Route::resource('employee', EmployeeController::class);

Route::get('/', function () {
    return view('index');
})->middleware(['user'])->name('dashboard');
require __DIR__.'/auth.php';
Route::post('login','LoginController@check');
Auth::routes();
Route::get('/index', [HomeController::class, 'index'])->name('home');
Route::controller(UserController::class)->group(function(){
    Route::get('users', 'index');
    Route::get('users-export', 'export')->name('users.export');
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    protected $table = 'roles';
    protected $primarykey = 'id';
    public $timestamps = true;
    protected $fillable = ['position'];
    public function employee()
    {
        return $this->hasMany(Employee::class, 'role_id', 'id');
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;
use App\Models\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->middleware(['isAdmin'])->except(['index']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $role = Role::all();
        return view('roles.list-role',[
                    'role' => $role,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('roles.create-role');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $role = Role::create([
            'position' => $request->input('position'),
        ]);
        $role->save();
        return redirect('role');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        return view('roles.edit-role')->with('role', $role);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::where('id', $id)
                    ->update([
                        'position'=>$request->input('position'),
                    ]);
        return redirect('/role');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::find($id);
        $role->delete();
        return redirect('/role');
    }
}

resources/views/roles/create-role.blade.php
@extends('layouts.body')
@section('index')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                <body>
                    <label for="inputStatus">Chức vụ</label>
                    <form style="margin-left: 650px;" class="row g-3 needs-validation"
                        action="{{ route('role.store') }}" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="col-md-2">
                            <label for="validationCustom01" class="form-label">Chức vụ</label>
                            <input type="text" class="form-control" id="validationCustom02"
                                name="position" placeholder="Nhập chức vụ" required>
                        </div>
                        <div class="col-12" style="margin-top:10px; ">
                            <button class="btn btn-primary" type="submit" >Thêm chức vụ</button>
                        </div>
                    </form>
                </body>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/roles/edit-role.blade.php
@extends('layouts.body')
@section('index')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                    </div>
                    <body>
                        <form style="margin-left: 650px ;" class="row g-3 needs-validation"
                        action="{{ route('role.update', $role->id) }}" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                            <input type="hidden" name="id" value="{{ $role->id }}">
                        <div class="col-md-2">
                            <label for="validationCustom01" class="form-label">Chức vụ</label>
                            <input type="text" class="form-control" id="validationCustom01" name="position"
                            placeholder="" value="{{ $role->position }}">
                        </div>
                        <div class="col-12">
                        <button class="btn btn-primary" type="submit" style="margin-top:10px;">Nhấn để sửa !</button>
                        </div>
                        </form>
                    </body>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/roles/list-role.blade.php
@extends('layouts.body')
@section('index')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Danh sách chức vụ</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Trang chủ</li>
                        <li class="breadcrumb-item active">Danh sách chức vụ</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Chức vụ</th>
                                        @if (auth()->user()->level == 0)
                                        <th>Sửa</th>
                                        <th>Xóa</th>
                                        @endif
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach( $role as $value)
                                    <tr>
                                        <th scope="row"><?=$value["id"]; ?></th>
                                        <td>{{ $value->position }}</td>
                                        @if (auth()->user()->level == 0)
                                        <td>
                                            <a href="{{ route('role.edit', $value->id) }}"><button type='submit' class='btn bg-yellow    btn-flat'  name=''><i class='fa fa-edit'></i></button></a>
                                        </td>
                                        <td>
                                            <form action="{{ route('role.destroy', $value->id) }}" method="POST" onclick="return confirm('Are you sure?')">
                                                @csrf
                                                @method('DELETE')
                                                <button type='submit' class='btn bg-red btn-flat' data-toggle='modal' data-target='#exampleModal'><i class='fa fa-trash'></i></button></a>
                                            </form>
                                        </td>
                                        @endif
                                    </tr>
                                @endforeach
                                </tbody>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection