routes/web.php
<?php
use Illuminate\Support\Facades\Auth;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::group(function () {
    Route::middleware('user')->group(function () {
        Route::resource('department', DepartmentController::class);
        Route::resource('role', RoleController::class);
        Route::resource('employee', EmployeeController::class);
     });
// })
// ->middleware(['isAdmin' excep()]);
// Route::get('/department', [DepartmentController::class, 'index'])->name('home');
// Route::get('/department/create', [DepartmentController::class, 'create'])->name('home');
// Route::post('/department', [DepartmentController::class, 'store'])->name('home');
// Route::get('/department/', [HomeController::class, 'index'])->name('home');
// Route::get('/index', [HomeController::class, 'index'])->name('home');



Route::middleware(['user'])->group(function () {

});

//         Route::resource('department', DepartmentController::class);
//         Route::resource('role', RoleController::class);
//         Route::resource('employee', EmployeeController::class);

Route::get('/', function () {
    return view('index');
})->middleware(['user'])->name('dashboard');
require __DIR__.'/auth.php';
Route::post('login','LoginController@check');
Auth::routes();
Route::get('/index', [HomeController::class, 'index'])->name('home');
Route::controller(UserController::class)->group(function(){
    Route::get('users', 'index');
    Route::get('users-export', 'export')->name('users.export');
});

resources/views/employes/create-employee.blade.php
@extends('layouts.body')
@section('index')
<div class="content-wrapper">
    <section class="content" style="margin-left:400px;">
<div class="row">
<div class="col-md-6">
<div class="card card-primary" >
    <div class="card-header">
    <h3 class="card-title" >Thêm thông tin nhân viên</h3>
    </div>
    <form style="" class="row g-3 needs-validation"
            action="{{ route('employee.store') }}" method="POST"
            enctype="multipart/form-data">
            @csrf
    <div class="card-body">
        <div class="form-group">
            <label for="inputName">Tên</label>
            <input type="text" class="form-control" id="validationCustom02"name="ten"  required>
        </div>
        <div class="form-group">
            <label for="inputClientCompany">Email</label>
            <input type="email" id="inputClientCompany" class="form-control" name="mail"required>
        </div>

        <div class="form-group">
            <label for="inputStatus">Chức vụ</label>
            <select id="inputStatus" class="form-control custom-select" name="chucvu" >
                @foreach ($roles as $role)
                <option value="{{ $role->id }}">{{ $role->position }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="inputStatus">Phòng ban</label>
            <select id="inputStatus" class="form-control custom-select" name="phongban" >
                @foreach ($departments as $department)
                <option value="{{ $department->id }}">{{ $department->name }}</option>
                @endforeach
            </select>
        </div>
    <div class="col-12">
                <button class="btn btn-primary" type="submit" >Thêm</button>
            </div>
        </form>
    <!-- /.card-body -->
</div>
<!-- /.card -->
</div>
</div>
</section>
</div>
@endsection

resources/views/employes/edit-employee.blade.php
@extends('layouts.body')
@section('index')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Chỉnh sửa thông tin nhân viên</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">


                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content" style="margin-left:400px;">
            <div class="row">
                <div class="col-md-6">
                <div class="card card-primary" >
                    <form style="" class="row g-3 needs-validation"
                            action="{{ route('employee.update', $employes->id) }}" method="POST"
                            enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <input type="hidden" name="id" value="">
                    <div class="card-body">
                    <div class="form-group">
                        <label for="inputName">Tên</label>
                    <input type="text" class="form-control" id="validationCustom02"name="ten" value="{{ $employes->name }}"  required>
                    </div>
                    <div class="form-group">
                        <label for="inputStatus">Chức vụ</label>
                        <select id="inputStatus" class="form-control custom-select" name="chucvu" required>
                            <option value="{{ $employes->role->id }}">{{ $employes->role->position }}</option>
                            @foreach ($roles as $role)
                            <option value="{{ $role->id }}">{{ $role->position }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="inputStatus">Phòng ban</label>
                        <select id="inputStatus" class="form-control custom-select" name="phongban" required>
                            <option value="{{ $employes->department->id }}">{{ $employes->department->name }}</option>
                            @foreach ($departments as $department)
                            <option value="{{ $department->id }}">{{ $department->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="inputClientCompany">Email</label>
                        <input type="email" id="inputClientCompany" class="form-control" name="mail"value="{{ $employes->email }}">
                    </div>
                    <div class="col-12">
                                <button class="btn btn-primary" type="submit" >Nhấn để sửa</button>
                            </div>
                        </form>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
                </div>


            </div>
            </section>
    <!-- /.content -->
</div>
@endsection

resources/views/employes/list-employee.blade.php
@extends('layouts.body')
@section('index')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Danh sách nhân viên</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Trang chủ</li>
                        <li class="breadcrumb-item active">Danh sách nhân viên</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div colspan="3">
                                <a class="btn btn-warning float-end" href="{{ route('users.export') }}">Export User Data</a>
                            </div>
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Tên </th>
                                        <th>Email</th>
                                        <th>Chức vụ</th>
                                        <th>Phòng ban</th>
                                        @if (auth()->user()->level == 0)
                                        <th>Sửa</th>
                                        <th>Xóa</th>
                                        @endif
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach( $employes as $employee)

                                    <tr>
                                        <th scope="row"><?=$employee["id"]; ?></th>
                                        <td>{{ $employee->name }}</td>
                                        <td>{{ $employee->email }}</td>
                                        <td>{{ @$employee->role->position }}</td>
                                        <td>{{ @$employee->department->name }}</td>
                                        {{-- <td></td> --}}
                                        @if (auth()->user()->level == 0)
                                        <td>
                                            <a href="{{ route('employee.edit', $employee->id) }}"><button type='submit' class='btn bg-yellow    btn-flat'  name=''><i class='fa fa-edit'></i></button></a>
                                        </td>
                                        <td>
                                            <form action="{{ route('employee.destroy', $employee->id) }}" method="POST" onclick="return confirm('Are you sure?')">
                                                @csrf
                                                @method('DELETE')
                                                <button type='submit' class='btn bg-red btn-flat' data-toggle='modal' data-target='#exampleModal'><i class='fa fa-trash'></i></button></a>
                                            </form>
                                        </td>
                                        @endif
                                    </tr>
                                @endforeach

                                </tbody>

                            </table>
                            <thead style="margin-left: 950px">{{ $employes->links()  }}</thead>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection